"""empty message

Revision ID: 361af747d91f
Revises: 51590a0425fd
Create Date: 2026-06-22 19:23:01.729382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361af747d91f'
down_revision = '51590a0425fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_memos_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_memos_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
