"""empty message

Revision ID: 51590a0425fd
Revises: 52b5d524951f
Create Date: 2026-06-22 17:08:15.666855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51590a0425fd'
down_revision = '52b5d524951f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
